### PR TITLE
Small edit suggestion

### PR DESCRIPTION
**Pull request by ghost**
As far i know not all file blocks ask for storage permission

### CODE REVIEW

**Comment by iyxan23** [comment]
I agree with you, but maybe add some information on how to grant read and write permission, because not all sketchware users know what does "READ and WRITE Storage permission" mean.

**Review by ghost — COMMENTED** [review]
Pull request edit

**Review by iyxan23 — APPROVED** [review]

**Review by iyxan23 — APPROVED** [review]

**Comment by ToastcodeDev** [comment]
Toast aproved

**Comment by iyxan23** [comment]
Already merged

**Pull request merged**
